services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: transactionsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./0db-init:/docker-entrypoint-initdb.d  # any .sql in /docker-entrypoint-initdb.d/ runs automatically...
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build: ./payment-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  fraud-service:
    build: ./fraud-service
    depends_on:
      - kafka
      - postgres

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - postgres

