version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper


# local kafka test...
# docker compose -f docker-compose.kafka.yaml up -d
  # docker ps

# cd into each service dir
  # build: mvn clean package
  # run: mvn spring-boot:run

# send post requests via curl...

# docker logs kafka


# just in case:
  # sudo -u postgres psql
  # CREATE DATABASE transactiondb;

  # INSERT INTO transactions (transaction_id, user_id, qty, location, timestamp, status, risk_score)
  # VALUES
  # ('tx-100', 'user-1', 200, 'London', NOW(), 'APPROVED', 10),
  # ('tx-101', 'user-1', 15000, 'Tokyo', NOW(), 'FLAGGED', 85),
  # ('tx-102', 'user-2', 50, 'Paris', NOW(), 'APPROVED', 5);

