version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  payment-service:
    build: ./payment-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  fraud-service:
    build: ./fraud-service
    depends_on:
      - kafka

  notification-service:
    build: ./notification-service
    depends_on:
      - kafka