server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: fraud-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ed.transaction_processing.common.event.TransactionEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://postgres:5432/transactionsdb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
